server:
  port: 8001
spring:
  application:
    # 微服务名称
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源的类型
    driver-class-name: com.mysql.cj.jdbc.Driver    #驱动
    url: jdbc:mysql://localhost:3306/cloud2020?serverTimezone=UTC&useSSL=false
    username: root
    password: '@Root123'

mybatis:
  mapperLocations: classpath:mapper/*.xml  # mapper文件路径
  type-aliases-package: com.springcloud.pojo # 扫描实体类取别名

eureka:
  client:
    # false 表示不想注册中心注册自己，true注册到服务中心
    register-with-eureka: true
    # false表示自己就是注册中心，职责就是维护服务实例，并不需要检索服务,true表示从EurekaServer撞去已有的注册信息，(集群必须设置为true才能配合ribbon使用负载均衡)
    fetch-registry: true
    service-url:
      #设置与Eureka server的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://localhost:7001/eureka
